package trafficlight.ILightMode
typedef UInt32 ModeType;
struct DirectionColor {
    UInt8 r;
    UInt8 y;
    UInt8 g;
}
typedef ModeType DirectionMode;
struct CrossedDirectionsMode {
    DirectionMode dir0;
    DirectionMode dir1;
    sequence<ModeType, 100> sq;
}
typedef sequence<UInt8, 100> TDSeq;
typedef sequence<array<CrossedDirectionsMode, 100>, 100> TDSeq3;
struct QQ {
    TDSeq3 qw;
}
interface {
    SetMode(
        in CrossedDirectionsMode obj, in DirectionMode val, in TDSeq seq, in string<30> str,
        out DirectionColor oobj, out QQ oval, out sequence<TDSeq, 100> oseq);
}
